// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuxatrzpdqbuobarogva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1eGF0cnpwZHFidW9iYXJvZ3ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDE1NTEsImV4cCI6MjA3MDgxNzU1MX0.qcBiEQRcxQVo0RgEWXZS8ghwXBfgYYIJsDPkObVwS20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});